### ISSUE TITLE
Outstanding work for v1

### ISSUE THREAD

**Issue by jongeorge1** [corvus-dotnet/Corvus.EventStore#9]
The following items are implemented, but require specs:
- Basic event storage over Cosmos, Azure Blob.
- Event publishing for Cosmos event store via the Cosmos change feed.

The following items require implementation:
- Event publishing for Azure Blob event store via the Event Grid blob events
- All stream aggregation
- Snapshot reading/writing

**Comment by mwadams** [comment]
I am closing this issue as we have had a rethink.
